version: '3'

services:
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USER_NAME}
      MYSQL_PASSWORD: ${USER_PASSWD}
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    ports:
      - "3306:3306"
  web:
    build: .
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
    - "8000:8000"
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin
    container_name: myadmin
    links:
      - db
    environment:
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
